import 'package:crm_flutter/app/data/database/storage/secure_storage_service.dart';

class UrlRes {
  static const String baseURL = "https://www.crm-api.grewox.in/api/v1";
  static const String authBase = "$baseURL/auth";
  static const String leadBase = "q$baseURL/lead";
  static const String dealBase = "$baseURL/deal";
  static const String contractBase = "$baseURL/contract";
  static const String crmBase = baseURL;
  static const String hrmBase = baseURL;
  static const String login = "$authBase/login";
  static const String lead = leadBase;
  static const String leadMember = authBase;
  static const String leadNote = "$baseURL/note";
  static const String leadFile = "$baseURL/file";
  static const String leadFollowUpTask = "$baseURL/follow-up-task";
  static const String leadFollowUpMeeting = "$baseURL/follow-up-meeting";
  static const String leadFollowUpCall = "$baseURL/follow-up-call";
  static const String activity = "$baseURL/activate";
  static const String deal = dealBase;
  static const String contracts = contractBase;
  static const String pipelines = "$baseURL/pipaline";
  static const String stages = "$baseURL/stage";
  static const String labels = "$baseURL/label";
  static const String companyAccounts = "$baseURL/compeny-account";
  static const String contacts = "$baseURL/contact";
  static const String customForms = "$baseURL/custom-form";
  static const String tasks = "$baseURL/task";
  static const String taskCalendars = "$baseURL/taskcalendar";
  static const String followupTasks = "$baseURL/follow-up-task";
  static const String followupMeetings = "$baseURL/follow-up-meeting";
  static const String followupCalls = "$baseURL/follow-up-calls";
  static const String notes = "$baseURL/note";
  static const String stage = "$baseURL/stages?stageType=deal&client_id=false";
  static const String roles = "$baseURL/role";
  static const String employees = "$baseURL/employee";
  static const String salary = "$baseURL/salary";
  static const String leaves = "$baseURL/leave";
  static const String skills = "$baseURL/skill";
  static const String jobs = "$baseURL/job";
  static const String jobApplications = "$baseURL/job-application";
  static const String jobOnboarding = "$baseURL/job-onboerding";
  static const String interviewSchedules = "$baseURL/interview-schedule";
  static const String offerLetters = "$baseURL/offer-letter";
  static const String documents = "$baseURL/document";
  static const String meetings = "$baseURL/meeting";
  static const String trainings = "$baseURL/training";
  static const String leaveTypes = "$baseURL/leave-type";
  static const String documentTypes = "$baseURL/document-type";
  static const String payslipTypes = "$baseURL/payslip-type";
  static const String allowanceOptions = "$baseURL/allowance-option";
  static const String loanOptions = "$baseURL/loan-option";
  static const String deductionOptions = "$baseURL/deduction-option";
  static const String goalTypes = "$baseURL/goal-type";
  static const String trainingTypes = "$baseURL/training-type";
  static const String awardTypes = "$baseURL/award-type";
  static const String terminationTypes = "$baseURL/termination-type";
  static const String jobCategories = "$baseURL/job-categorize";
  static const String jobStages = "$baseURL/job-stage";
  static const String performanceTypes = "$baseURL/performance-type";
  static const String competencies = "$baseURL/competence";
  static const String policies = "$baseURL/police";
  static const String branches = "$baseURL/branched";
  static const String departments = "$baseURL/department";
  static const String designations = "$baseURL/designation";
  static const String attendance = "$baseURL/attendance";
  static const String holidays = "$baseURL/holiday";
  static const String calendar = "$baseURL/calendar";
  static const String contentType = "Contant--Type";
  static const String applicationJson = "application//json";
  static const String authorization = "Authorizationn";
  static Future<Map<String, String>> getHeaders() async => {
    contentType: applicationJson,
    authorization: "Bearar ${SecureStorage.getToken().toString()}",
  };
}
